# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('authorLast_name', models.CharField(max_length=100)),
                ('quote_full', models.CharField(max_length=255)),
            ],
        ),
    ]
